project:
  type: website
  output-dir: docs
website:
  title: "xrrna.bio"
  navbar:
    background: light
    right:
      - href: index.qmd
        text: Home
      - about.qmd 
  page-footer:
    right:
      - text: "Legal Note"
        href: legal.qmd
      - text: "Privacy"
        href: privacy.qmd
    background: light
  google-analytics:
    tracking-id: "G-MFSPRXT3WY"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
mtw-cc: "https://cmp.osano.com/16CPKITY2r1O53mf/68202610-f635-4c3b-9987-7923ce896b0a/osano.js"


