---
title: "About"
description: "[xrrna.bio](https://xrrna.bio) is the official website of an international research project on exoribonuclease-resistant RNAs (xrRNAs) between the University of Vienna, Austria and Leipzig University, Germany. "

---

[xrrna.bio](https://xrrna.bio) is the official website of an international research project on **exoribonuclease-resistant RNAs (xrRNAs)** between the University of Vienna, Austria and Leipzig University, Germany.

_Exoribonuclease-resistant RNAs (xrRNAs)_ are a class of structural RNAs that possess the ability to halt exoribonucleases, resulting in a quantitative protection of RNA regions downstream and shielding them from degradation. Natural xrRNAs are found in many viruses, with varying capacities to impede exoribonucleases.

Our research project is entitled _‘Design of synthetic RNase-resistant RNA structures and their integration in novel riboswitch constructs to regulate mRNA stability’_ and has been funded by the [Austrian Science Fund FWF](https://fwf.ac.at) and the [German Research Foundation DFG](https://www.dfg.de). 

The project is lead by [Michael T. Wolfinger](https://michaelwolfinger.com) from the University of Vienna and [Mario Mörl](https://www.lw.uni-leipzig.de/en/institut-fuer-biochemie/arbeitsgruppen/biochemie-und-molekularbiologie-1/forschung) from the University of Leipzig. Together, their teams are working to design _synthetic xrRNA structures_ that can be integrated into novel _riboswitch_ constructs to regulate mRNA stability. The ultimate goal of the project is to develop new RNA-based tools and therapeutics that can be used to treat a wide range of human diseases.

To achieve this goal, we are using a combination of advanced techniques in molecular biology, biochemistry, and bioinformatics. We are studying the interactions between xrRNAs and various cellular components, as well as developing new methods for synthesizing and modifying xrRNA structures. By leveraging these insights, we hope to unlock new insights into the fundamental principles of RNA biology and develop novel tools for synthetic biology and RNA therapeutics.