---
title: "Legal Note / Impressum"
---

#### Informationen und Offenlegung gemäß §5 (1) ECG, § 25 MedienG, § 63 GewO und § 14 UGB

##### Websitebetreiber
Michael T. Wolfinger ([@mtwolfinger](https://twitter.com/mtwolfinger))  
[michaelwolfinger.com](https://michaelwolfinger.com)

  Bioinformatik und Computational Biology  
  Fakultät für Informatik  
  Universität Wien  
  Währinger Strasse 29  
  1090 Wien  

#### Urheberrecht

Die Inhalte dieser Website unterliegen, soweit dies rechtlich möglich ist, diversen Schutzrechten (u.a. dem Urheberrecht). Jegliche Verwendung/Verbreitung von bereitgestelltem Material, welche urheberrechtlich untersagt ist, bedarf schriftlicher Zustimmung des Websitebetreibers.

#### Haftungsausschluss

Trotz sorgfältiger inhaltlicher Kontrolle übernimmt der Websitebetreiber dieser Website keine Haftung für die Inhalte externer Links. Für den Inhalt der verlinkten Websites sind ausschließlich deren Betreiber verantwortlich. Sollten Sie dennoch auf ausgehende Links aufmerksam werden, welche auf eine Website mit rechtswidriger Tätigkeit/Information verweisen, ersuchen wir um dementsprechenden Hinweis, um diese nach § 17 Abs. 2 ECG umgehend zu entfernen. Die Urheberrechte Dritter werden vom Betreiber dieser Website mit größter Sorgfalt beachtet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden derartiger Rechtsverletzungen werden wir den betroffenen Inhalt umgehend entfernen.

#### Anwendbare Rechtsvorschrift

http://www.ris.bka.gv.at